### PR TITLE
Updated vendored libraries

### LINKED ISSUE #276: Compatibility with numpy 2.0
Numpy 2.0 is incoming with some breaking changes. It might require some adaptations and third party c++ library update (pybind11, xtensor-python)

### PR DESCRIPTION
**Pull request by JoOkuma**
Hi @PerretB , I updated the libraries, this should close #276 

It's passing on my environment with `numpy==2.0.0`.

If this gets merged, could we bump a version?

Note that I also removed an unused line in `include/higra/image/graph_image.hpp` to silence a warning.

### CODE REVIEW

**Comment by PerretB** [comment]
Hi Jordão, thank you for the PR. There is a problem with catch2, they switched from a single file header only model in v2 to a multi-header statically compiled library in v3. So moving to v3 requires a lot of changes, if you are ready to make them you are of course welcome, but it is also possible to stick to v2 for now :)

**Comment by JoOkuma** [comment]
Thanks for the heads up @PerretB , rolled back `catch2`

**Comment by JoOkuma** [comment]
Just a heads up, I updated the CI of the three latest versions of Python

**Comment by PerretB** [comment]
It seems that setuptools is being removed from default packages in 3.12 distributions. I think adding it there https://github.com/higra/Higra/blob/53e03e1751d0b9269a4626bba4fe368a186ed87a/.appveyor.yml#L44 (could be added to the other entries of the build matrix too) should fix the problem on Windows build (not sure why increasing Numpy version solved the issue on linux/macos builds, setuptools should probably also be explicitly added there)

**Comment by JoOkuma** [comment]
Hey @PerretB, thanks for the feedback.
I'm not familiar with this CI, I added the `setuptools` install where I thought it was more appropriate, feel free to edit if you disagree with it.

**Comment by PerretB** [comment]
ok indeed it's linked to this issue in xtensor https://github.com/xtensor-stack/xtensor/issues/2736 , already reported as compiler bug in MSVC https://developercommunity.visualstudio.com/t/lambda-fails-to-implicitly-capture-constexpr-value/610504

**Comment by PerretB** [comment]
@JoOkuma I will try to replicate the problem locally and see if I can find a fix

**Comment by PerretB** [comment]
@JoOkuma ok it's fixed. Do you mind creating a new clean PR with only required changes in small commits? Otherwise I'll do it during the week

**Comment by PerretB** [comment]
replaced by #278

**Pull request closed without merging**
